//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_employee_docs
    {
        public int idSchool { get; set; }
        public int idUser { get; set; }
        public int employee_number { get; set; }
        public string doc_name { get; set; }
    
        public virtual sys_school sys_school { get; set; }
    }
}
