//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_program_section
    {
        public sch_program_section()
        {
            this.sch_program_batch_student = new HashSet<sch_program_batch_student>();
        }
    
        public int idSection { get; set; }
        public int idSchool { get; set; }
        public int idProgram { get; set; }
        public string section { get; set; }
        public Nullable<int> idBuilding { get; set; }
        public string room { get; set; }
        public Nullable<int> capacity { get; set; }
    
        public virtual ICollection<sch_program_batch_student> sch_program_batch_student { get; set; }
        public virtual sys_program sys_program { get; set; }
        public virtual sys_school sys_school { get; set; }
    }
}
