//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_department
    {
        public sch_department()
        {
            this.sch_employee = new HashSet<sch_employee>();
        }
    
        public int idDepartment { get; set; }
        public int idSchool { get; set; }
        public string department_name { get; set; }
    
        public virtual sys_school sys_school { get; set; }
        public virtual ICollection<sch_employee> sch_employee { get; set; }
    }
}
