//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_fee_type
    {
        public sch_fee_type()
        {
            this.sch_program_batch_fee = new HashSet<sch_program_batch_fee>();
        }
    
        public int idFeeType { get; set; }
        public int idSchool { get; set; }
        public string name { get; set; }
    
        public virtual sys_school sys_school { get; set; }
        public virtual ICollection<sch_program_batch_fee> sch_program_batch_fee { get; set; }
    }
}
