//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_business
    {
        public sys_business()
        {
            this.sys_school = new HashSet<sys_school>();
        }
    
        public int idBusiness { get; set; }
        public System.DateTime ts_entered { get; set; }
        public Nullable<System.DateTime> ts_updated { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<sys_school> sys_school { get; set; }
    }
}
