//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOrbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vew_user_roles
    {
        public int iduser { get; set; }
        public int idschool { get; set; }
        public string displayname { get; set; }
        public int idrole { get; set; }
        public string role_name { get; set; }
        public int id { get; set; }
    }
}
