//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_parent
    {
        public sch_parent()
        {
            this.sch_student = new HashSet<sch_student>();
        }
    
        public int idUser { get; set; }
        public string father_guardian_name { get; set; }
        public string father_guardian_phone_no { get; set; }
        public string father_guardian_email { get; set; }
        public string father_guardian_occupation { get; set; }
        public string mother_name { get; set; }
        public string mother_phone_no { get; set; }
        public string mother_email { get; set; }
        public string mother_occupation { get; set; }
        public System.DateTime ts_entered { get; set; }
        public Nullable<System.DateTime> ts_updated { get; set; }
    
        public virtual sys_user sys_user { get; set; }
        public virtual ICollection<sch_student> sch_student { get; set; }
    }
}
