//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_user_roles
    {
        public int id { get; set; }
        public int idSchool { get; set; }
        public int idUser { get; set; }
        public int idRole { get; set; }
        public bool isactive { get; set; }
        public int entered_by { get; set; }
        public System.DateTime ts_entered { get; set; }
        public int last_updated_by { get; set; }
        public System.DateTime ts_updated { get; set; }
    }
}
