//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_employee
    {
        public int idSchool { get; set; }
        public int idUser { get; set; }
        public int employee_number { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public Nullable<System.DateTime> WorkEndDate { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> PassingYear { get; set; }
        public string University { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string ESIPFNumber { get; set; }
        public string PanNumber { get; set; }
        public string AdharNumber { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string mobilenumber { get; set; }
        public string AlternateNumber { get; set; }
        public string cv_path { get; set; }
        public string addressproof_path { get; set; }
    
        public virtual sch_department sch_department { get; set; }
        public virtual sys_school sys_school { get; set; }
        public virtual sys_user sys_user { get; set; }
    }
}
