//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_expense_trans
    {
        public int id { get; set; }
        public int idSchool { get; set; }
        public int expense_type_id { get; set; }
        public Nullable<System.DateTime> expense_date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string remarks { get; set; }
        public Nullable<int> approved_by { get; set; }
        public Nullable<System.DateTime> approved_dt { get; set; }
        public string approved_remarks { get; set; }
        public System.DateTime ts_entered { get; set; }
        public System.DateTime ts_updated { get; set; }
        public int last_updated_by { get; set; }
        public int entered_by { get; set; }
        public int idExpensestatus { get; set; }
        public string mode_of_payment { get; set; }
        public Nullable<int> cheque_dd_no { get; set; }
        public string issue_bank { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual sch_expense_type sch_expense_type { get; set; }
        public virtual sys_school sys_school { get; set; }
    }
}
