//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_sms_service
    {
        public int id { get; set; }
        public int idSchool { get; set; }
        public string ServiceProvidername { get; set; }
        public string Sender { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public System.DateTime ts_entered { get; set; }
        public Nullable<System.DateTime> ts_updated { get; set; }
        public int ts_updated_by { get; set; }
        public int Balance { get; set; }
        public string WebApi { get; set; }
        public string BalanceWebapi { get; set; }
    }
}
