//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_sms_notification
    {
        public int id { get; set; }
        public int idSchool { get; set; }
        public string To { get; set; }
        public string Body { get; set; }
        public Nullable<int> sentBy { get; set; }
        public System.DateTime ts_entered { get; set; }
        public Nullable<System.DateTime> ts_updated { get; set; }
    
        public virtual sys_school sys_school { get; set; }
        public virtual sys_user sys_user { get; set; }
    }
}
