//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sch_student
    {
        public int idSchool { get; set; }
        public int idUser { get; set; }
        public int admission_number { get; set; }
        public Nullable<System.DateTime> admission_date { get; set; }
        public Nullable<System.DateTime> transfer_date { get; set; }
        public bool is_active { get; set; }
        public System.DateTime ts_entered { get; set; }
        public Nullable<System.DateTime> ts_updated { get; set; }
        public int idParent { get; set; }
    
        public virtual sch_parent sch_parent { get; set; }
        public virtual sys_school sys_school { get; set; }
        public virtual sys_user sys_user { get; set; }
    }
}
