//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SOEntities : DbContext
    {
        public SOEntities()
            : base("name=SOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sch_department> sch_department { get; set; }
        public virtual DbSet<sch_employee> sch_employee { get; set; }
        public virtual DbSet<sch_employee_docs> sch_employee_docs { get; set; }
        public virtual DbSet<sch_expense_attachment> sch_expense_attachment { get; set; }
        public virtual DbSet<sch_expense_trans> sch_expense_trans { get; set; }
        public virtual DbSet<sch_expense_type> sch_expense_type { get; set; }
        public virtual DbSet<sch_fee_discount> sch_fee_discount { get; set; }
        public virtual DbSet<sch_fee_payment_plan> sch_fee_payment_plan { get; set; }
        public virtual DbSet<sch_fee_term> sch_fee_term { get; set; }
        public virtual DbSet<sch_fee_type> sch_fee_type { get; set; }
        public virtual DbSet<sch_mynotification> sch_mynotification { get; set; }
        public virtual DbSet<sch_notification> sch_notification { get; set; }
        public virtual DbSet<sch_parent> sch_parent { get; set; }
        public virtual DbSet<sch_program_batch> sch_program_batch { get; set; }
        public virtual DbSet<sch_program_batch_fee> sch_program_batch_fee { get; set; }
        public virtual DbSet<sch_program_batch_student> sch_program_batch_student { get; set; }
        public virtual DbSet<sch_program_section> sch_program_section { get; set; }
        public virtual DbSet<sch_sms_notification> sch_sms_notification { get; set; }
        public virtual DbSet<sch_sms_service> sch_sms_service { get; set; }
        public virtual DbSet<sch_student> sch_student { get; set; }
        public virtual DbSet<sch_teacher> sch_teacher { get; set; }
        public virtual DbSet<sch_user_roles> sch_user_roles { get; set; }
        public virtual DbSet<sys_academic_year> sys_academic_year { get; set; }
        public virtual DbSet<sys_business> sys_business { get; set; }
        public virtual DbSet<sys_country> sys_country { get; set; }
        public virtual DbSet<sys_program> sys_program { get; set; }
        public virtual DbSet<sys_program_model> sys_program_model { get; set; }
        public virtual DbSet<sys_program_type> sys_program_type { get; set; }
        public virtual DbSet<sys_roles> sys_roles { get; set; }
        public virtual DbSet<sys_school> sys_school { get; set; }
        public virtual DbSet<sys_states> sys_states { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<sch_fee_schedule> sch_fee_schedule { get; set; }
        public virtual DbSet<vew_user_roles> vew_user_roles { get; set; }
        public virtual DbSet<vew_user_security_roles> vew_user_security_roles { get; set; }
        public virtual DbSet<vewNotification> vewNotifications { get; set; }
    
        [DbFunction("SOEntities", "fn_expense_rpt_month_view")]
        public virtual IQueryable<fn_expense_rpt_month_view_Result> fn_expense_rpt_month_view(Nullable<int> fin_year, Nullable<int> sch_id)
        {
            var fin_yearParameter = fin_year.HasValue ?
                new ObjectParameter("fin_year", fin_year) :
                new ObjectParameter("fin_year", typeof(int));
    
            var sch_idParameter = sch_id.HasValue ?
                new ObjectParameter("sch_id", sch_id) :
                new ObjectParameter("sch_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_expense_rpt_month_view_Result>("[SOEntities].[fn_expense_rpt_month_view](@fin_year, @sch_id)", fin_yearParameter, sch_idParameter);
        }
    
        [DbFunction("SOEntities", "fn_sch_expense_consol_month_view")]
        public virtual IQueryable<fn_sch_expense_consol_month_view_Result> fn_sch_expense_consol_month_view(Nullable<int> fin_year, Nullable<int> sch_id)
        {
            var fin_yearParameter = fin_year.HasValue ?
                new ObjectParameter("fin_year", fin_year) :
                new ObjectParameter("fin_year", typeof(int));
    
            var sch_idParameter = sch_id.HasValue ?
                new ObjectParameter("sch_id", sch_id) :
                new ObjectParameter("sch_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_sch_expense_consol_month_view_Result>("[SOEntities].[fn_sch_expense_consol_month_view](@fin_year, @sch_id)", fin_yearParameter, sch_idParameter);
        }
    
        [DbFunction("SOEntities", "fn_sch_expense_type_month_view")]
        public virtual IQueryable<fn_sch_expense_type_month_view_Result> fn_sch_expense_type_month_view(Nullable<int> fin_year, Nullable<int> sch_id)
        {
            var fin_yearParameter = fin_year.HasValue ?
                new ObjectParameter("fin_year", fin_year) :
                new ObjectParameter("fin_year", typeof(int));
    
            var sch_idParameter = sch_id.HasValue ?
                new ObjectParameter("sch_id", sch_id) :
                new ObjectParameter("sch_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_sch_expense_type_month_view_Result>("[SOEntities].[fn_sch_expense_type_month_view](@fin_year, @sch_id)", fin_yearParameter, sch_idParameter);
        }
    }
}
