//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_program
    {
        public sys_program()
        {
            this.sch_program_batch = new HashSet<sch_program_batch>();
            this.sch_program_section = new HashSet<sch_program_section>();
        }
    
        public int idProgram { get; set; }
        public string name { get; set; }
        public Nullable<int> duration { get; set; }
        public int idProgramType { get; set; }
        public int idProgramModel { get; set; }
    
        public virtual ICollection<sch_program_batch> sch_program_batch { get; set; }
        public virtual ICollection<sch_program_section> sch_program_section { get; set; }
        public virtual sys_program_model sys_program_model { get; set; }
        public virtual sys_program_type sys_program_type { get; set; }
        public virtual sys_program_type sys_program_type1 { get; set; }
    }
}
