//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_program_type
    {
        public sys_program_type()
        {
            this.sys_program = new HashSet<sys_program>();
            this.sys_program1 = new HashSet<sys_program>();
        }
    
        public int idProgramType { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<sys_program> sys_program { get; set; }
        public virtual ICollection<sys_program> sys_program1 { get; set; }
    }
}
