//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vewNotification
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public System.DateTime ts_entered { get; set; }
        public string ToList { get; set; }
        public string jsonToList { get; set; }
        public string To { get; set; }
        public string sentByname { get; set; }
        public Nullable<int> sentby { get; set; }
        public int idschool { get; set; }
    }
}
